services:
  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    restart: unless-stopped
    ports:
      - ${IT_TOOLS_PORT}:80
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "it-tools"

