services:
  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    restart: unless-stopped
    ports:
      - ${IT_TOOLS_PORT}:80
    healthcheck:
      test: "curl -k http://localhost:80 || exit 1"
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 20s
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "it-tools"
