services:
  sharelatex:
    restart: always
    image: sharelatex/sharelatex
    container_name: sharelatex
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - ${OVERLEAF_PORT}:80
    expose:
      - 80
    links:
      - mongo
      - redis
    stop_grace_period: 60s
    volumes:
      - ./data/sharelatex:/var/lib/overleaf
      ########################################################################
      ####  Server Pro: Uncomment the following line to mount the docker  ####
      ####             socket, required for Sibling Containers to work    ####
      ########################################################################
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      OVERLEAF_APP_NAME: ${OVERLEAF_APP_NAME}
      OVERLEAF_MONGO_URL: ${OVERLEAF_MONGO_URL}
      OVERLEAF_REDIS_HOST: ${OVERLEAF_REDIS_HOST}
      REDIS_HOST: ${REDIS_HOST}
      ENABLED_LINKED_FILE_TYPES: ${ENABLED_LINKED_FILE_TYPES}
      ENABLE_CONVERSIONS: ${ENABLE_CONVERSIONS}
      EMAIL_CONFIRMATION_DISABLED: ${EMAIL_CONFIRMATION_DISABLED}
      TEXMFVAR: ${TEXMFVAR}
      # VIRTUAL_HOST: ${VIRTUAL_HOST}
      # OVERLEAF_SITE_URL: ${OVERLEAF_SITE_URL}
      # OVERLEAF_NAV_TITLE: ${OVERLEAF_NAV_TITLE}
      # OVERLEAF_HEADER_IMAGE_URL: ${OVERLEAF_HEADER_IMAGE_URL}
      # OVERLEAF_ADMIN_EMAIL: ${OVERLEAF_ADMIN_EMAIL}
      # OVERLEAF_LEFT_FOOTER: ${OVERLEAF_LEFT_FOOTER}
      # OVERLEAF_RIGHT_FOOTER: ${OVERLEAF_RIGHT_FOOTER}
      # OVERLEAF_EMAIL_FROM_ADDRESS: ${OVERLEAF_EMAIL_FROM_ADDRESS}
      # OVERLEAF_EMAIL_AWS_SES_ACCESS_KEY_ID: ${OVERLEAF_EMAIL_AWS_SES_ACCESS_KEY_ID}
      # OVERLEAF_EMAIL_AWS_SES_SECRET_KEY: ${OVERLEAF_EMAIL_AWS_SES_SECRET_KEY}
      # OVERLEAF_EMAIL_SMTP_HOST: ${OVERLEAF_EMAIL_SMTP_HOST}
      # OVERLEAF_EMAIL_SMTP_PORT: ${OVERLEAF_EMAIL_SMTP_PORT}
      # OVERLEAF_EMAIL_SMTP_SECURE: ${OVERLEAF_EMAIL_SMTP_SECURE}
      # OVERLEAF_EMAIL_SMTP_USER: ${OVERLEAF_EMAIL_SMTP_USER}
      # OVERLEAF_EMAIL_SMTP_PASS: ${OVERLEAF_EMAIL_SMTP_PASS}
      # OVERLEAF_EMAIL_SMTP_TLS_REJECT_UNAUTH: ${OVERLEAF_EMAIL_SMTP_TLS_REJECT_UNAUTH}
      # OVERLEAF_EMAIL_SMTP_IGNORE_TLS: ${OVERLEAF_EMAIL_SMTP_IGNORE_TLS}
      # OVERLEAF_EMAIL_SMTP_NAME: ${OVERLEAF_EMAIL_SMTP_NAME}
      # OVERLEAF_EMAIL_SMTP_LOGGER: ${OVERLEAF_EMAIL_SMTP_LOGGER}
      # OVERLEAF_CUSTOM_EMAIL_FOOTER: ${OVERLEAF_CUSTOM_EMAIL_FOOTER}
      # ENABLE_CRON_RESOURCE_DELETION: ${ENABLE_CRON_RESOURCE_DELETION}
      # SANDBOXED_COMPILES: ${SANDBOXED_COMPILES}
      # SANDBOXED_COMPILES_SIBLING_CONTAINERS: ${SANDBOXED_COMPILES_SIBLING_CONTAINERS}
      # SANDBOXED_COMPILES_HOST_DIR: ${SANDBOXED_COMPILES_HOST_DIR}
      # OVERLEAF_LDAP_URL: ${OVERLEAF_LDAP_URL}
      # OVERLEAF_LDAP_SEARCH_BASE: ${OVERLEAF_LDAP_SEARCH_BASE}
      # OVERLEAF_LDAP_SEARCH_FILTER: ${OVERLEAF_LDAP_SEARCH_FILTER}
      # OVERLEAF_LDAP_BIND_DN: ${OVERLEAF_LDAP_BIND_DN}
      # OVERLEAF_LDAP_BIND_CREDENTIALS: ${OVERLEAF_LDAP_BIND_CREDENTIALS}
      # OVERLEAF_LDAP_EMAIL_ATT: ${OVERLEAF_LDAP_EMAIL_ATT}
      # OVERLEAF_LDAP_NAME_ATT: ${OVERLEAF_LDAP_NAME_ATT}
      # OVERLEAF_LDAP_LAST_NAME_ATT: ${OVERLEAF_LDAP_LAST_NAME_ATT}
      # OVERLEAF_LDAP_UPDATE_USER_DETAILS_ON_LOGIN: ${OVERLEAF_LDAP_UPDATE_USER_DETAILS_ON_LOGIN}
      # OVERLEAF_TEMPLATES_USER_ID: ${OVERLEAF_TEMPLATES_USER_ID}
      # OVERLEAF_NEW_PROJECT_TEMPLATE_LINKS: ${OVERLEAF_NEW_PROJECT_TEMPLATE_LINKS}
      # OVERLEAF_PROXY_LEARN: ${OVERLEAF_PROXY_LEARN}

  mongo:
    restart: always
    image: mongo:5.0
    container_name: sharelatex-mongo
    expose:
      - 27017
    volumes:
      - ./data/mongo_data:/data/db
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    # extra_hosts:
    #   - "mongo:127.0.0.1"

  redis:
    restart: always
    image: redis:7-alpine
    container_name: sharelatex-redis
    expose:
      - 6379
    volumes:
      - ./data/redis_data:/data
