services:
  watchtower:
    restart: unless-stopped
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP
      - WATCHTOWER_SCHEDULE
      - WATCHTOWER_NOTIFICATIONS
      - WATCHTOWER_NOTIFICATION_URL
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - /etc/localtime:/etc/localtime:ro
