api:
  dashboard: true
  debug: true
log:
  level: DEBUG
  # filePath: /var/log/traefik.log
  # format: json
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  # file:
  #   filename: /config.yaml
certificatesResolvers:
  myresolver:
    tailscale: {}
