services:
  portainer:
    image: portainer/portainer-ee:2.21.2
    container_name: portainer
    restart: always
    ports:
      - "${PORTAINER_PORT}:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
