recorder:
mobile_app:
http:
  server_port: !env_var HOMEASSISTANT_PORT
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.0/8
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    - ::1
