services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      # - data:/config
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    healthcheck:
      test: "curl -k http://localhost:8123 || exit 1"
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    privileged: true
    environment:
      - HOMEASSISTANT_PORT
      - PROXY_IP
    network_mode: host
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "homeassistant"
      tsdproxy.container_port: ${HOMEASSISTANT_PORT}

volumes:
  data:
