services:
  glance:
    image: glanceapp/glance
    volumes:
      - ./config/glance.yml:/app/glance.yml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8001:8080
    restart: unless-stopped
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "glance"
