services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsd-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
      - ./config/:/config
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  data:
