pages:
  - name: Homelab
    columns:
      - size: full
        widgets:
          - type: bookmarks
            groups:
              - title: Monitoring & Infrastructure
                links:
                  - title: Dozzle
                    url: https://dozzle.griffin-frog.ts.net/
                  - title: Beszel
                    url: https://beszel.griffin-frog.ts.net/
                  # - title: Uptime Kuma
                  #   url: https://uptime-kuma.griffin-frog.ts.net/
              - title: Automation & Workflows
                links:
                  - title: n8n
                    url: https://n8n.griffin-frog.ts.net/
                  - title: Home Assistant
                    url: https://homeassistant.griffin-frog.ts.net/
              - title: Data Management
                links:
                  - title: Ghostfolio
                    url: https://ghostfolio.griffin-frog.ts.net/
                  - title: Paperless‑ngx
                    url: https://paperless-ngx.griffin-frog.ts.net/
              - title: Media
                links:
                  - title: Immich
                    url: https://immich.griffin-frog.ts.net/
              - title: Miscellaneous
                links:
                  - title: Mazanoke
                    url: https://mazanoke.griffin-frog.ts.net/
                  - title: Stirling‑PDF
                    url: https://stirling-pdf.griffin-frog.ts.net/
                  - title: It‑Tools
                    url: https://it-tools.griffin-frog.ts.net/
      - size: small
        widgets:
          - type: calendar

          - type: weather
            location: Aveiro, Portugal

          - type: markets
            markets:
              - symbol: BTC-EUR
                name: Bitcoin
              - symbol: ETH-EUR
                name: Ethereum
              - symbol: SOL-EUR
                name: Solana
              - symbol: DOGE-EUR
                name: Doge
              - symbol: SPY
                name: S&P 500

  - name: News
    columns:
      - size: full
        widgets:
          - type: rss
            limit: 15
            collapse-after: 6
            cache: 3h
            feeds:
              - url: https://world.hey.com/dhh/feed.atom
                title: DHH
              - url: https://blog.pragmaticengineer.com/rss/
                title: The Pragmatic Engineer
              - url: https://martinfowler.com/feed.atom
                title: Martin Fowler
              # - url: https://dev.to/feed
              #   title: Dev.to
              # - url: http://www.producthunt.com/feed
              #   title: Product Hunt

          - type: hacker-news
            limit: 15
            collapse-after: 3

          # - type: videos
          #   channels:
          #     - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
          #     - UCv6J_jJa8GJqFwQNgNrMuww # ServeTheHome
          #     - UCOk-gHyjcWZNj3Br4oxwh0A # Techno Tim

          # - type: reddit
          #   subreddit: selfhosted
