services:
  mazanoke:
    container_name: mazanoke
    image: ghcr.io/civilblur/mazanoke:latest
    ports:
      - ${MAZANOKE_PORT}:80
    restart: unless-stopped
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "mazanoke"
