services:
  mazanoke:
    container_name: mazanoke
    image: ghcr.io/civilblur/mazanoke:latest
    ports:
      - ${MAZANOKE_PORT}:80
    restart: unless-stopped
    healthcheck:
      test: "curl -k http://localhost:80 || exit 1"
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 20s
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "mazanoke"
